### ISSUE TITLE
About novel dataset inference without meta file

### ISSUE THREAD

**Issue by KevinGuo07** [Omni6DPose/GenPose2#12]
Hi @Jiyao06 , thanks for your great work!

While inference on aligned dataset has good performance, I try to infer on my own novel dataset which **only includes RGB and Depth data**, however I find it's still hard to debug the _data_init_  part and **meta.json** is still necessary to infer. 
#9  as this issue address, how can I modify infer.script to achieve inference w/o meta.json?

**Comment by KevinGuo07** [comment]
This problem is solved, i add corresponding camera parameters of the dataset and make them to .json files like the origin ones in ROPE

**Comment by warb1370** [comment]
I’ve successfully added the corresponding camera parameters for my dataset and saved them as .json files similar to those in the ROPE dataset, and inference now works. However, I’m still not sure how to configure the object part in the JSON file.

**Comment by warb1370** [comment]
@Jiyao06 I’ve successfully added the corresponding camera parameters for my dataset and saved them as .json files similar to those in the ROPE dataset, and inference now works. However, I’m still not sure how to configure the object part in the JSON file.

**Comment by fitz0401** [comment]
> This problem is solved, i add corresponding camera parameters of the dataset and make them to .json files like the origin ones in 

I would like to ask how the inference effect of custom data is?

**Comment by wbq00** [comment]
> 我已成功为我的数据集添加了相应的相机参数，并将它们保存为 .json 文件，类似于 ROPE 数据集中的参数，现在推理可以正常工作。但是，我仍然不确定如何在 JSON 文件中配置对象部分。

Hello, I would like to know how the meta.json file in the ROPE dataset is generated, especially the content of the “objects” section. I am planning to use my own dataset for 6D pose annotation, and I am unsure how to create the meta.json file when making the dataset. Thank you for your reply!

**Comment by Jiyao06** [comment]
If you need to perform new data annotation, please look at Sec. 3.2 of our paper ([https://arxiv.org/pdf/2406.04316](https://arxiv.org/pdf/2406.04316)). If you only need to perform inference, the information in the "object" section of the meta.json file is not required.

**Comment by wbq00** [comment]
> 如果您需要执行新的数据注释，请查看我们论文 （https://arxiv.org/pdf/2406.04316） 的第 3.2 节。如果只需要进行推理，则不需要 meta.json 文件的 “object” 部分中的信息。

Hello,哥. I'm using the depth camera of Orbbec. The camera intrinsic parameters I exported are as follows, which are divided into the intrinsic parameters of the color image and the depth image. I've tried both, and I've annotated the medicine box, but it failed in both cases.

[ColorIntrinsic]
fx = 2255.962158
fy = 2253.743652
cx = 1897.314209
cy = 1087.265259
width = 3840
height = 2160

[DepthIntrinsic]
fx = 375.993683
fy = 375.623932
cx = 316.219025
cy = 181.210876
width = 640
height = 360

The following is the JSON file I wrote. I'd like you to take a look at it and tell me what's wrong that caused the annotation to fail. Thank you!

{
    "objects": {
        
    },
    "camera": {
        "quaternion": [
            1,
            0,
            0,
            0
        ],
        "translation": [
            0,
            0,
            0
        ],
        "intrinsics": {
            "fx": 375.993683,
            "fy": 375.623932,
            "cx": 316.219025,
            "cy": 181.210876,
            "width": 640,
            "height": 360
        },
        "scene_obj_path": "",
        "background_image_path": "",
        "background_depth_path": "",
        "distances": [],
        "kind": ""
    },
    "scene_dataset": "real",
    "env_param": {},
    "face_up": true,
    "concentrated": false,
    "comments": "real scan video data",
    "runtime_seed": -1,
    "baseline_dis": 0,
    "emitter_dist_l": 0
}

**Comment by Jiyao06** [comment]
> > 如果您需要执行新的数据注释，请查看我们论文 （[https://arxiv.org/pdf/2406.04316）](https://arxiv.org/pdf/2406.04316%EF%BC%89) 的第 3.2 节。如果只需要进行推理，则不需要 meta.json 文件的 “object” 部分中的信息。
> 
> Hello,哥. I'm using the depth camera of Orbbec. The camera intrinsic parameters I exported are as follows, which are divided into the intrinsic parameters of the color image and the depth image. I've tried both, and I've annotated the medicine box, but it failed in both cases.
> 
> [ColorIntrinsic] fx = 2255.962158 fy = 2253.743652 cx = 1897.314209 cy = 1087.265259 width = 3840 height = 2160
> 
> [DepthIntrinsic] fx = 375.993683 fy = 375.623932 cx = 316.219025 cy = 181.210876 width = 640 height = 360
> 
> The following is the JSON file I wrote. I'd like you to take a look at it and tell me what's wrong that caused the annotation to fail. Thank you!
> 
> { "objects": {
> 
> ```
> },
> "camera": {
>     "quaternion": [
>         1,
>         0,
>         0,
>         0
>     ],
>     "translation": [
>         0,
>         0,
>         0
>     ],
>     "intrinsics": {
>         "fx": 375.993683,
>         "fy": 375.623932,
>         "cx": 316.219025,
>         "cy": 181.210876,
>         "width": 640,
>         "height": 360
>     },
>     "scene_obj_path": "",
>     "background_image_path": "",
>     "background_depth_path": "",
>     "distances": [],
>     "kind": ""
> },
> "scene_dataset": "real",
> "env_param": {},
> "face_up": true,
> "concentrated": false,
> "comments": "real scan video data",
> "runtime_seed": -1,
> "baseline_dis": 0,
> "emitter_dist_l": 0
> ```
> 
> }

1. Could you please clarify what you mean by "failed in both cases"? Are there any specific errors or issues you're encountering?

2. Based on your description, here are a few potential areas to check:
 - Have you aligned the depth image to the RGB image? The network typically requires the aligned depth and RGB images as input.
 - When using the alignment operation, make sure to use the intrinsic parameters of the reference camera as your subsequent parameters. It's common to use the downsampled RGB as the reference camera. In this case, you should use the corresponding intrinsics of the downsampled RGB camera.

**Comment by Jiyao06** [comment]
Now, you can refer to the `Real-time camera stream inference` section.
